version: '3.7'
services:
  app:
    image: ${DOCKER_IMAGE}
    command: ["start"]
    ports:
      - 4200
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - development

networks:
  development:
    name: nginx-proxy
    external: true

volumes:
  node_modules:
